default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: git_responsive_development

test:
  <<: *default
  database: git_responsive_test

production:
  <<: *default
  database: git_responsive_production
  username: git_responsive
  password: <%= ENV['GIT_RESPONSIVE_DATABASE_PASSWORD'] %>
